server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cmfz?characterEncoding=UTF-8
  http:
    encoding:
      force-request: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  redis:
    host: 192.168.252.128
    port: 6379
    database: 0

mybatis:
  mapper-locations: classpath:com/yang/mapper/*.xml #指定mapper文件位置
  type-aliases-package: com.yang.entity #给实体类起别名
logging:
  level:
    com.yang.dao: debug
